### ISSUE TITLE
squadron-5.1.0/lib/src/xplat/_helpers.dart:17:14: Error: Member not found: 'DateTime.timestamp'

### ISSUE THREAD

**Issue by techouse** [d-markey/squadron#22]
Hey! :)

I upgraded to v5.10 and tried running the code generation but got this error

```
[INFO] Precompiling build script......
[WARNING] ../../.pub-cache/hosted/pub.dev/squadron-5.1.0/lib/src/xplat/_helpers.dart:17:14: Error: Member not found: 'DateTime.timestamp'.
    DateTime.timestamp().difference(_sqEpoch).inMicroseconds;
             ^^^^^^^^^
```

Looks like a missing `DateTime` import.

**Comment by d-markey** [comment]
`DataTime` is from `dart:core` so it can't be a missing import problem. I looked up Dart documentation and `timestamp()` is actually a new constructor in Dart 3 but it doesn't come with a `@Since` annotation to warn against this.
* Dart 2.19.6 --> https://api.dart.dev/stable/2.19.6/dart-core/DateTime-class.html
* Dart 3.0.0 --> https://api.dart.dev/stable/3.0.0/dart-core/DateTime-class.html

**Comment by techouse** [comment]
You're awesome! ♥️ I'll test it tomorrow morning!

**Comment by d-markey** [comment]
Publishing right now
