### ISSUE TITLE
WASM Support

### ISSUE THREAD

**Issue by AlexDochioiu** [d-markey/squadron#37]
Hey @d-markey . Would be great to update squadron to the new dart:js_interop since flutter 3.22.0 added stable wasm support (which doesn't work with dart:html and js/js).

**Comment by d-markey** [comment]
A little bit of feedback on progress: it will take some time before I pulbish an update, but I'm getting there!

Debugging is complicated, but I've fixed several issues already. One key finding is compatibility between Dart and Wasm type systems. JavaScript had its caveats, it seems Wasm has even more. E.g. `int`s posted from the main thread come through as `double` on Wasm side. Careful handling of types will be essential, and this will impact [squadron_builder](https://github.com/d-markey/squadron_builder) as well.

![image](https://github.com/d-markey/squadron/assets/1548408/6b6917b4-9ade-4d04-9397-1eb620eb1246)

**Comment by d-markey** [comment]
Still working on it. I've come into issues that were present in past versions of Squadron, in relation to streaming operations. These should now be fixed!

The latest commit provides a version that will run nicely on native and pure JavaScript platforms. Also, I believe you don't have to migrate your own code to `package:web`, it should also work even when using `dart:html`.

Wasm-compatibility is there, in the sense that Squadron 6.0 has been migrated from `dart:html` to `package:web`. Apps using Squadron and Squadron Web Workers can now be compiled to Web Assembly.

But at runtime, there are still a few glitches essentially related to numbers: it seems that Dart `int`s sent to a Web Assembly Web Worker come through as `double`s in wasm (at least that's what I'm seeing on Chrome), causing runtime errors when entering the Dart realm again (id est: Dart --> Browser (window) --> Browser (Web Worker) --> Dart).

Debugging/testing Web support is also extremely time consuming with 4 different combinations of JS/Wasm window + JS/Wasm Web Worker. Currently I only have automated tests for native and JS/JS. JS/Wasm, Wasm/JS and Wasm/Wasm are handled manually.

If you're curious, you can try running the tests in the various configurations. The process is:

1. in a terminal, run `.\tool\serve_tests.bat`
2. in a different terminal, execute `./tool/compile_all_tests.bat`
3. point your browser to http://localhost:8080/browser-tests/ and start testing

Any change to code in Squadron, tests or workers will typically require to execute step 2 again and reload the HTML test console...

Quite a journey!

**Comment by sabin26** [comment]
Is there any upstream dart/flutter issue for this int-double runtime error ?

**Comment by d-markey** [comment]
There's one here https://github.com/dart-lang/sdk/issues/55203.

However the example makes no use of Web workers, so it looks like a Dart/Dart issue. I'm not sure this is fixable (in Dart SDK) when Web workers are used because data leaves the Dart type system when a message is posted (be it js or wasm) and then reenters it (as JSObject) when the message is received. Something must be done to fully recover Dart types ie. call `dartify()` and the int/double difference. JS only kno

**Comment by sabin26** [comment]
Does squadron_builder also need to be updated ?

**Comment by d-markey** [comment]
Yes, Squadron 6 has a few breaking changes in terms of API. squadron_builder will have to be adapted, and it will handle the int/double conversions where it can.

But if you have implemented custom types and marshalers, some conversions will remain your responsibility.

Also note that there are other issues in wasm, eg. https://github.com/dart-lang/sdk/issues/52714. This one could impact performance.

**Comment by d-markey** [comment]
For what it's worth, I've pushed a commit to squadron_builder and support int/double casting in generated code. The github version forces use of squadron 6.0 from github (cf. https://github.com/d-markey/squadron_builder/blob/main/pubspec.yaml#L16) so you might want to test squadron and squadron_builder directly from github instead of pub.dev.

Also, I might be able to have automated tests work for wasm client (= main thread) thanks to https://github.com/dart-lang/test/pull/2262. If this works, testing wasm/js in addition to js/js should be easy. Then to test wasm/wasm and js/wasm, it should only be a matter of running the tests twice (with JS workers then with Wasm workers)  :-)

**Comment by sabin26** [comment]
I have few issues when using squadron and squadron builder from github for WASM Compatibility.

1. I have to override the dependency for squadron. Without the override, the pub get throws from `squadron_builder`
```dart
dependencies:
  squadron:
    git:
      url: https://github.com/d-markey/squadron
      ref: main
dependency_overrides:
  squadron:
    git:
      url: https://github.com/d-markey/squadron
      ref: main
dev_dependencies:
  squadron_builder:
    git:
      url: https://github.com/d-markey/squadron_builder
      ref: main

```

2. What is the replacement API for `SquadronException.registerExceptionDeserializer` & `SquadronException.unregisterExceptionDeserializer` ?

3. `CanceledException` is not exported from library

**Comment by d-markey** [comment]
1. Yes, because squadron_builder from GitHub already overrides the squadron dependency to fetch it from GitHub.

2. There is an ExceptionManager now attached to the worker. You can register custom exception serializers via this member.

3. I have published a separate package for cancelation tokens and exceptions, cf. https://pub.dev/packages/cancelation_token

**Comment by jpohhhh** [comment]
Thank you *very* much for your hard work on this, have an issue, I can split it out to another GitHub issue if that's better. 

1. I'm using squadron & squadron_builder at HEAD, same setup in pubspec as sabin26 above. 

2. I run build_runner, then run a shell script to convert the web.g.dart files to JS. ([^1^] in footer)

3. That results in an error `A value of type 'String' can't be returned from a function with return type 'Uri'.` on these lines in the web.g.dart files: `EntryPoint $getUtf8DecoderServiceActivator() =>
    'lib/squadron/utf8_decoder/utf8_decoder_service.web.g.dart.js';`
    
4. If I hardcode it to ex. Uri.file('lib/squadron/utf8_decoder/utf8_decoder_service.web.g.dart.js'), it compiles, and app launches, but the services aren't working

5. Checking backwards, I see impl/web/_typedefs.dart defines `typedef EntryPoint = Uri;` so it does seem right to expect URI. But, the squadron_builder tests & examples have Strings returned from EntryPoint, so I feel like I must be missing something.


[^1^] Shell script:
```
for service in "${services[@]}"; do
  file="lib/squadron/${service}.web.g.dart"
  output_file="${file}.js"
  
  echo "Compiling $file"
  dart compile js -O2 "$file" -o "$output_file"
done
```

**Comment by d-markey** [comment]
Hello,

Thanks for the report, but that would be a squadron_builder issue. Could you file it under https://github.com/d-markey/squadron_builder/issues ?

**Comment by jpohhhh** [comment]
Absolutely, I'll file an issue for Uri there: in case someone stumbles across a similar issue later, tl;dr adding Uri.parse works just fine. Beyond that, I was getting confused about how running dhttpd x Flutter WASM worked. (i.e. dhttpd was 404'ing on the JS files)

**Comment by d-markey** [comment]
Hello @jpohhhh, things should now compile properly as I've fixed the `Uri` issue.

Regarding the runtime issue with dhttpd, can you provide more details? With WASM support, there are now a mix of possibilities to run your app:

* main app compiled to JS and Web workers compiled to JS 
* main app compiled to Wasm and Web workers compiled to JS
* main app compiled to JS and Web workers compiled to Wasm 
* main app compiled to Wasm and Web workers compiled to Wasm

First, can you confirm everything still works fine when you go JS/JS?

Then from your message, I understand you compiled your main (Flutter UI per se) app to Wasm but are still compiling Web workers to JS. This should work fine with squadron_builder without any modification.

Now if you want Wasm Web Workers, there's a new `wasm` option I've just added to `SquadronService`. To have Squadron load Wasm Web workers, make sure your worker service class is decorated with `@SquadronService(web: true, wasm: true, baseUrl: '<base URI where the compiled Web worker file is generated/copied>')` or `@SquadronService.web(wasm: true, baseUrl: '<base URI where the compiled Web worker file is generated/copied>')`.

For instance, your Flutter app is typically compiled to a "/web" directory located in your project root folder and that's where dhttpd would serve it from. You need to generate the Web worker files somewhere under that directory so that dhttpd can serve them. Say you create a "/workers" directory under "/web": in that case, you should make sure your shell script generates or copies the compiled JS file to "/web/workers", and you should use `/workers` as the `baseUrl` in `@SquadronService`.

**Comment by sabin26** [comment]
Should this be changed ?

From:

`dart compile js lib/src/browser/service_worker.dart -o web/service_worker.dart.js`

To:

`dart compile wasm lib/src/browser/service_worker.dart -o web/service_worker.dart.wasm`

**Comment by d-markey** [comment]
If you want Web Assembly workers, yes.

Please note that compiling to wasm will also produce a .mjs file (its purpose is to load the web assembly file) but Squadron doesn't need it. Only the .wasm file needs be published to your web server.

**Comment by d-markey** [comment]
My bad: the .mjs file is not the Web assembly loader, and is required so it must be published to your Web server alongside the .wasm file.

**Comment by d-markey** [comment]
Just sharing this also: to have Flutter run as wasm, your Web server must provide specific headers 

For instance:
`Cross-Origin-Embedder-Policy: credentialless`
`Cross-Origin-Opener-Policy: same-origin`

This is important if you're running eg. with dhttpd. It will make sure `window.crossOriginIsolated` return `true`. See https://developer.mozilla.org/en-US/docs/Web/API/Window/crossOriginIsolated

**Comment by d-markey** [comment]
Closing this as completed! I'm finaliizing work on squadron_builder and will publish packages on pub.dev when everything's ready.

In the meantime, you can use squadron + squadron_builder from git source in your `pubspec.yaml` file.

**Comment by d-markey** [comment]
Version 6 is available, please refer to Squadron's changelog for breaking changes.
