### ISSUE TITLE
Hive database worker

### ISSUE THREAD

**Issue by anidotnet** [d-markey/squadron#39]
Hi @d-markey could you please provide an example of hive database worker using squadron (provided if it is possible to do so)?

**Comment by d-markey** [comment]
Hi there,

I don't know if this would work, it all depends on Hive really.

FYI it seems Hive runs on Isar, and in the past Isar failed to work in Web Workers. See https://github.com/d-markey/squadron/issues/7#issuecomment-1087922527. Back then, I investigated a bit and I believe this is is due to Isar relying on DOM features, which are not available in Web Workers. An issue was also opened, see https://github.com/isar/isar/issues/324.

Closing this one for now!
