### ISSUE TITLE
[Critical BUG][v6] Hanging requests 

### ISSUE THREAD

**Issue by AlexDochioiu** [d-markey/squadron#46]
There seem to be some issue where some requests can end up hanging.

Here, running the same operation 4 times, ends up stuck in the first call.
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/898e835c-73ca-485b-bb0b-0cc029270b89">

Here, running the same operation 5 times, but **ignoring and not awaiting the fist call** works fine.
<img width="577" alt="image" src="https://github.com/user-attachments/assets/6e73cbf5-9695-4d18-ae11-250b6e1d451f">

Additional info:
1. The first call in this test **is not** the first call to the worker method used internally. There's already been a previous call that returned correctly!
2. I noticed this issue on both VM and JS Web worker, both in test and in actual app.
3. Using the same setup, I never had this issue in squadron v5
4. I am re-using a worker pool for everything (see screenshot below) by invoking `useWorker`

<img width="621" alt="image" src="https://github.com/user-attachments/assets/d0aad86b-e1dd-4874-bba7-b9a0a39b50f4">

**Comment by d-markey** [comment]
The test with 4 awaits fails systematically, or on some occasions only?

**Comment by AlexDochioiu** [comment]
It always fails, and always on the first awaited call. I am now looking to potentially debug myself the cause too (inside squadron).

One extra thing that I noticed in my own usage (and potentially the root of this issue) is that my `useWorker` usage has a nested call.

<img width="715" alt="image" src="https://github.com/user-attachments/assets/89d3df53-4b9a-4134-8d30-a8588ad119bd">

P.s. I inlined the "nested" usage in above screenshot to be clearer.

**Comment by d-markey** [comment]
Another question: have you tried with a worker instead of a worker pool?

**Comment by d-markey** [comment]
So I understand `pubAccount` is not a worker, but it has a private worker pool `_sharedWorker` (or maybe from a parent class?) and the worker pool can be used via `useWorker`?

**Comment by AlexDochioiu** [comment]
Using worker instead of worker pool works correctly.

So it is probably something to do with the worker pool task scheduling.

**Comment by AlexDochioiu** [comment]
`pubAccount` is not a worker. It's just some class using a worker pool internally (via the `useWorker` helper method that I added).

**Comment by AlexDochioiu** [comment]
There's another change that I made as part of the migration to v6. This change may actually be what caused the current issue.

Before, I used to have `maxParallel = 10` for worker pool. During the v6 migration, I removed this (effectively making it 1). Increasing this 2+ fixes the issue.

I think what's going on is effectively a deadlock caused by the nested `useWorker` scheduling a worker task inside a worker task. Because max parallel is 1, it cannot start the nested task because it waits on the parent task to complete (which would never happen).

Question is, why is it not running this inside a different worker? (maxWorkers is 10)

**Comment by AlexDochioiu** [comment]
⬆️ the above conclusion is a theory based on what I see. I did not actually debug yet to confirm this is indeed what's happening.

**Comment by AlexDochioiu** [comment]
It is nested, because the first task cannot finish without the second one running. And the second one may be in a deadlock waiting for the first one to finish.

If I compute `spendPubKey` directly from `w` it works fine.

**Comment by d-markey** [comment]
Actually `execute()` is not meant to be used by user code. It's public so squadron_builder can generate the code to send a work request via the pool, but it should be considered internal.

Why don't you use the pool directly? Id est, instead of calling `useWorker((w) => w.xxxx(...))` you should be able to call `_sharedWorker.xxxx(...)` instead.

**Comment by AlexDochioiu** [comment]
Not sure why but I thought I need to call execute 🤔 . It's been added a while ago and never looked back.

**Comment by d-markey** [comment]
Nope, you don't have to. It's very possible that `execute()` is not reentrant, I never checked that so I guess I'll add more tests for that.

I find your approach has something interesting because `execute()` allows your code to "capture" a worker and then make several requests to that worker, so in the context of a pool you can do this:

```dart
await myPool.execute((worker) {
  await worker.doThis();
  await worker.thenThat();
  await worker.andThisToo();
});
```

However -- thinking as I'm typing --  that's also as many roundtrips to the worker, so more cloning especially on Web...

Also beware that the worker provided to your lambda is not really captured, I mean there is no exclusive access to this worker. If `maxParallel` is > 1, another call to the pool might as well use that same worker to handle another work request. So workers used in a pool must absolutely be stateless otherwise you will end up with weird effects.

So yes, nesting calls to `execute()` is most probably an antipattern and should be avoided.

The only advantage I can see is that the code above has captured a worker and will not need to reenter the pool again, and wait to be scheduled to finish the work. For instance, the code above should be functionally equivalent to:

```dart
await myPool.doThis();
await myPool.thenThat();
await myPool.andThatToo();
```

But in terms of performance/efficiency, using the pool 3 times in a row is likely slower because each individual call requires scheduling. If other worker requests have been posted to the pool in the meantime, calls to `thenThat()` or `andThisToo()` will also be delayed.

So using `execute()` with multiple calls to the worker only needs to be scheduled once, which looks like a bonus. Just make sure you don't nest calls to `execute()`.

That's an interesting use case, never thought of that 😄 

NOTE: you might also be better off implementing a single service method `doThisThenThatAndThatToo()` to eliminate roundtrips between the worker and the main thread. You said you "inlined" the nested usage, so I suppose there's some code running on your main thread between worker invocations...

**Comment by d-markey** [comment]
If it works for you, can this issue be closed?

**Comment by AlexDochioiu** [comment]
Happy to close this issue, yes.
