### ISSUE TITLE
beginner questions

### ISSUE THREAD

**Issue by stephane-archer** [d-markey/squadron#47]
What is this `baseUrl` in `@SquadronService`, I'm not sure what I should put in my case.
Why would you do something else than `TargetPlatform.all` in `targetPlatform`? What would happen if I were running the code on a platform not selected
Can I just annotate the function we want to paralyze and not create a dedicated class annotated with  `@SquadronService`?
```
@SquadronService(baseUrl: '~/workers', targetPlatform: TargetPlatform.all)
base class HelloWorld {
  @SquadronMethod()
  FutureOr<String> hello([String? name]) {
    name = name?.trim() ?? 'World';
    return 'Hello, $name!';
  }
}
```

**Comment by d-markey** [comment]
> What is this `baseUrl` in `@SquadronService`, I'm not sure what I should put in my case. 

Because if you develop for the web, the layout of your deployed workers (after compilation to JS or Wasm) will likely be different from the folder structure of your Dart/Flutter project (original Dart code).

> Why would you do something else than `TargetPlatform.all` in `targetPlatform`? What would happen if I were running the code on a platform not selected

Because you may have workers using features specific to a platform, eg 64 bit `int`s that JS does not support.

> Can I just annotate the function we want to paralyze and not create a dedicated class annotated with `@SquadronService`?
> 
> ```
> @SquadronService(baseUrl: '~/workers', targetPlatform: TargetPlatform.all)
> base class HelloWorld {
>   @SquadronMethod()
>   FutureOr<String> hello([String? name]) {
>     name = name?.trim() ?? 'World';
>     return 'Hello, $name!';
>   }
> }
> ```

Because Squadron needs a class implementing the methods you want to run on dedicated threads. JavaScript Functions cannot be sent to a Web worker, so Squadron makes sure an instance of your service class exists in the worker to run your method off the main thread.
